controller_list:
  - name: pos_joint_traj_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint]

  - name: gripper_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: [gripper140finger_joint]

  #
  # gripper_controller:
  #   type: effort_controllers/JointTrajectoryController
  #   joints:
  #     - gripper140finger_joint
  #   gains:
  #     gripper140finger_joint:
  #       p: 40
  #       d: 0
  #       i: 0
  #       i_clamp: 1
